#!/bin/sh

# Generates a file suitable for importing into GIMP based on
# playpal-base.lmp, and placed into doom.gpl

# File header
cat > doom.gpl <<EOF
GIMP Palette
Name: Doom
Columns: 16
#
EOF

od -An -tu1 -v playpal-base.lmp | 
awk '
{
    for (i = 1; i <= NF; i++) {
        rgb[count % 3] = $i
        if (count % 3 == 2)
            printf "%4d%4d%4d\n", rgb[0], rgb[1], rgb[2]
        count++
    }
}
END {
    if (count % 3 != 0)
        exit 1
}
' >> doom.gpl
