NB: This is all out of date now. I need to update it at some point

COPYING
	The modified BSD license the freedoom material is under
ChangeLog
	List of changes
CREDITS
	List of contributors

flats
	Floor textures
	The files in this directory are symlinks into subdirectories (1 
	directory for each author) 
flats_hi
	See patches_hi. High resolution flats.
graphics
	Graphics for menu, heads up display and status bar, etc.
levels
	levels.
	Currently we have 32 randomly generated slige levels here :)
lumps
	miscellaneous lumps. PLAYPAL and COLORMAP are assigned to cph.
musics
	musics.
patches
	Patches for wall textures.
	Organised the same as for flats.
patches_hi
	High resolution wall patches. These are in .png format, and are
	converted to tga by the build script
sounds
	Sounds
sprites
	Sprites
	We currently have the enemy sprites from Iikka keranens Povdoom in 
	here, these may be only temporary
textures
	Texture definitions - for TEXTURE1 and PNAMES

Build system:

Makefile
	Build makefile. Build everything or just certain bits
build
	Wrapper script for make. Redirect all stdout and stderr messages
	to build.output

buildcfg.txt
	The combined build spec file. Features specific to Doom1/Doom2/
	shareware builds are specified with #defines. This file is parsed
	by cpp (the GNU C PreProcessor) which generates the appropriate
	wadinfo.txt for the type of wad wanted. The file is also passed
	through wadinfo-builder.pl, which comments out all lines which
	refer to resources which have not yet been submitted (so the wad
	can still be built).

wadinfo.txt
	The deutex build file for the main build. Do not edit this file
	directly; use buildcfg.txt
wadinfo_sw.txt
	The deutex build file for the shareware build. Do not edit this
	file directly; use buildcfg.txt
wadinfo_iwad.txt
	The deutex build file for the iwad build. Do not edit this file
	directly; use buildcfg.txt. This is the same as wadinfo.txt except
	instead of missing resources being commented out, they are linked
	to dummy replacements.

