#!/usr/bin/env perl

use strict;
my %patches;

while (<>) {
	if (/^\*/) { 
		my ($name) = /^\*\s+(\w+)/;
		$name = uc $name;
		$patches{$name} = 1;
	}
}

print "; autogenerated patch list\n\n";

foreach (sort keys %patches) { print "$_\n"; }

