#!/usr/bin/env perl
# Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008
# Contributors to the Freedoom project.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of the freedoom project nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

use strict;
my %patches;

# Parse a TEXTURE1 file and generate a list of patches

sub parse_texture_file {

        while (<>) {
                if (/^\*/) { 
                        my ($name) = /^\*\s+(\w+)/;
                        $name = uc $name;
                        $patches{$name} = 1;
                }
        }

        print "; autogenerated patch list\n\n";

        foreach (sort keys %patches) { print "$_\n"; }
}

# Generate a full list of textures from the files in the
# patches/ directory

sub list_all_textures {
        print "; autogenerated patch list\n\n";

        foreach my $file (glob("patches/*.gif")) {
                if ($file =~ /\/(.*)\.gif/) {
                        print "$1\n";
                }
        }
}

if (scalar @ARGV == 0) {
        parse_texture_file();
} elsif ($ARGV[0] == "-a") {
        list_all_textures();
} else {
        print "Usage: extract-pnames.pl [-a]\n";
}

