#!/bin/sh

# OLD BUILD SCRIPT
# THIS IS DEPRECATED, USE 'make'

echo "use make"

exit

export DOOMWADDIR="/usr/share/games/doom"

# create the dynamic titlepic :)

cd graphics/titlepic
./create_caption
cd ../..

# update wadinfo.txt

./wadinfo-builder.pl < wadinfo.txt.real > wadinfo.txt

#---------------------------------------------------------
# build wad

echo "** main build **" > build.output
echo "** main build **" > build.errors
echo "main build"

rm -f wads/freedoom.wad
deutex -rgb 0 255 255 -lumps -patch -flats -sounds -musics -graphics -sprites -build wadinfo.txt wads/freedoom.wad >> build.output 2>> build.errors

# gzip wad

gzip < wads/freedoom.wad > wads/freedoom.wad.gz

#---------------------------------------------------------
# build levels wad

echo "** levels build **" >> build.output
echo "** levels build **" >> build.errors
echo "levels build"

rm -f wads/freedoom_levels.wad
deutex -levels -build wadinfo.txt wads/freedoom_levels.wad >> build.output 2>> build.errors

# gzip

gzip < wads/freedoom_levels.wad > wads/freedoom_levels.wad.gz

#---------------------------------------------------------
# build texture wad

echo "** textures build **" >> build.output
echo "** textures build **" >> build.errors
echo "texture build"

rm -f wads/freedoom_textures.wad
deutex -rgb 0 255 255 -patch -flats -build wadinfo.txt wads/freedoom_textures.wad >> build.output 2>> build.errors

gzip < wads/freedoom_textures.wad > wads/freedoom_textures.wad.gz

#---------------------------------------------------------
# build sprites wad

echo "** sprites build **" >> build.output
echo "** sprites build **" >> build.errors
echo "sprites build"

rm -f wads/freedoom_sprites.wad
deutex -sprites -rgb 0 255 255 -build wadinfo.txt wads/freedoom_sprites.wad >> build.output 2>> build.errors

gzip < wads/freedoom_sprites.wad > wads/freedoom_sprites.wad.gz

#---------------------------------------------------------
# build sounds wad

echo "** sounds build **" >> build.output
echo "** sounds build **" >> build.errors
echo "sounds build"

rm -f wads/freedoom_sounds.wad
deutex -sounds -musics -build wadinfo.txt wads/freedoom_sounds.wad >> build.output 2>> build.errors

echo "gzipping"

gzip < wads/freedoom_sounds.wad > wads/freedoom_sounds.wad.gz

# output

cat build.output build.errors

# md5sum

cd wads
md5sum `ls *.wad *.wad.gz` > freedoom.md5sum
cd ..
