#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause

import a2i_file
import sbi_file
import sys

if len(sys.argv) != 3:
    print(
        "Usage: %s <input filename> <output filename>" % sys.argv[0],
        file=sys.stderr,
    )
    sys.exit(-1)

data = a2i_file.read(sys.argv[1])
sbi_file.write(sys.argv[2], data)
