#!/usr/bin/env python
# SPDX-License-Identifier: BSD-3-Clause

import genmidi
import sys

if len(sys.argv) != 2:
	print >> sys.stderr, "Usage: %s <filename>" % sys.argv[0]
	sys.exit(-1)

from config import INSTRUMENTS, PERCUSSION

genmidi.write(sys.argv[1], INSTRUMENTS + PERCUSSION)

