#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause

import genmidi
import sys

if len(sys.argv) != 2:
    print("Usage: %s <filename>" % sys.argv[0], file=sys.stderr)
    sys.exit(-1)

from config import INSTRUMENTS, PERCUSSION

genmidi.write(sys.argv[1], INSTRUMENTS + PERCUSSION)
